services:
  - type: web
    name: backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    env: node
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /healthcheck
